### ISSUE TITLE
[clarification request, or bug] Shortcut "ez" not printed in the list of suggestions

### ISSUE THREAD

**Issue by Wikinaut** [georgjaehnig/serchilo-drupal#161]
I recently added shortcut "ez", what works, but what is **not listed in the list of suggestions** in the searchengine bar, or findfind entry.

A problem of your database query (for short strings) ? But other short strings like "g" or "db" do work w/o problems.

**Comment by georgjaehnig** [comment]
Fixed. The problem was caused because you 

- first added the shortcut to a site namespace, where it did not get approved
- then moved it to you user namespace – and wrongly it got still not approved
- Because it was not approved, it does not show in the suggestions (correct behaviour)

By now, every save to a shortcut in the *user* namespace by its *user* get approved. Just save the shortcut again.

**Comment by Wikinaut** [comment]
Confirmed: working now. 

This explains also some other problems I noticed in the last weeks, but which I could not explain.

Great- Thanks!
